apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-ui-nonprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-ui-nonprod
  template:
    metadata:
      labels:
        app: hello-world-ui-nonprod
    spec:
      containers:
      - name: hello-world-ui-nonprod
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-ui-nonprod
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: hello-world-ui-nonprod
