apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-ui-nonprod
  labels:
    app: hello-world-ui-nonprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-ui-nonprod
  template:
    metadata:
      labels:
        app: hello-world-ui-nonprod
    spec:
      containers:
      - name: hello-world-ui-nonprod
        image: jmbactista/hello-world-nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-ui-nonprod
spec:
  selector:
    app: hello-world-ui-nonprod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer 
